/* address_field.c generated by valac 0.44.3, the Vala compiler
 * generated from address_field.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#define PICOLAN_TYPE_ADDRESS_FIELD (picolan_address_field_get_type ())
#define PICOLAN_ADDRESS_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PICOLAN_TYPE_ADDRESS_FIELD, picolanAddressField))
#define PICOLAN_ADDRESS_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PICOLAN_TYPE_ADDRESS_FIELD, picolanAddressFieldClass))
#define PICOLAN_IS_ADDRESS_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PICOLAN_TYPE_ADDRESS_FIELD))
#define PICOLAN_IS_ADDRESS_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PICOLAN_TYPE_ADDRESS_FIELD))
#define PICOLAN_ADDRESS_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PICOLAN_TYPE_ADDRESS_FIELD, picolanAddressFieldClass))

typedef struct _picolanAddressField picolanAddressField;
typedef struct _picolanAddressFieldClass picolanAddressFieldClass;
typedef struct _picolanAddressFieldPrivate picolanAddressFieldPrivate;
typedef struct _picolanParamSpecAddressField picolanParamSpecAddressField;

struct _picolanAddressField {
	GTypeInstance parent_instance;
	volatile int ref_count;
	picolanAddressFieldPrivate * priv;
};

struct _picolanAddressFieldClass {
	GTypeClass parent_class;
	void (*finalize) (picolanAddressField *self);
};

struct _picolanAddressFieldPrivate {
	guint8 bytes[32];
};

struct _picolanParamSpecAddressField {
	GParamSpec parent_instance;
};

static gint picolanAddressField_private_offset;
static gpointer picolan_address_field_parent_class = NULL;

gpointer picolan_address_field_ref (gpointer instance);
void picolan_address_field_unref (gpointer instance);
GParamSpec* picolan_param_spec_address_field (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void picolan_value_set_address_field (GValue* value,
                                      gpointer v_object);
void picolan_value_take_address_field (GValue* value,
                                       gpointer v_object);
gpointer picolan_value_get_address_field (const GValue* value);
GType picolan_address_field_get_type (void) G_GNUC_CONST;
void picolan_address_field_set_address (picolanAddressField* self,
                                        guint8 addr);
gboolean picolan_address_field_get_address (picolanAddressField* self,
                                            guint8 addr);
guint8* picolan_address_field_get_bytes (picolanAddressField* self,
                                         gint* result_length1);
static guint8* _vala_array_dup1 (guint8* self,
                          int length);
picolanAddressField* picolan_address_field_new (void);
picolanAddressField* picolan_address_field_construct (GType object_type);
static void picolan_address_field_finalize (picolanAddressField * obj);

static inline gpointer
picolan_address_field_get_instance_private (picolanAddressField* self)
{
	return G_STRUCT_MEMBER_P (self, picolanAddressField_private_offset);
}

void
picolan_address_field_set_address (picolanAddressField* self,
                                   guint8 addr)
{
	gint bf = 0;
	gint bit = 0;
	guint8 val = 0U;
	guint8 _tmp0_;
	g_return_if_fail (self != NULL);
	bf = addr / 8;
	bit = addr % 8;
	_tmp0_ = self->priv->bytes[bf];
	val = _tmp0_;
	val = val | (1 << bit);
	self->priv->bytes[bf] = val;
}

gboolean
picolan_address_field_get_address (picolanAddressField* self,
                                   guint8 addr)
{
	gboolean result = FALSE;
	gint bf = 0;
	gint bit = 0;
	guint8 mask = 0U;
	guint8 _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	bf = addr / 8;
	bit = addr % 8;
	mask = (guint8) (1 << bit);
	_tmp0_ = self->priv->bytes[bf];
	result = ((gint) (_tmp0_ & mask)) == 0;
	return result;
}

static guint8*
_vala_array_dup1 (guint8* self,
                  int length)
{
	return g_memdup (self, length * sizeof (guint8));
}

guint8*
picolan_address_field_get_bytes (picolanAddressField* self,
                                 gint* result_length1)
{
	guint8* result = NULL;
	guint8* _tmp0_;
	gint _tmp0__length1;
	guint8* _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (self->priv->bytes != NULL) ? _vala_array_dup1 (self->priv->bytes, 32) : ((gpointer) self->priv->bytes);
	_tmp0__length1 = 32;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}

picolanAddressField*
picolan_address_field_construct (GType object_type)
{
	picolanAddressField* self = NULL;
	self = (picolanAddressField*) g_type_create_instance (object_type);
	return self;
}

picolanAddressField*
picolan_address_field_new (void)
{
	return picolan_address_field_construct (PICOLAN_TYPE_ADDRESS_FIELD);
}

static void
picolan_value_address_field_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
picolan_value_address_field_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		picolan_address_field_unref (value->data[0].v_pointer);
	}
}

static void
picolan_value_address_field_copy_value (const GValue* src_value,
                                        GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = picolan_address_field_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
picolan_value_address_field_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
picolan_value_address_field_collect_value (GValue* value,
                                           guint n_collect_values,
                                           GTypeCValue* collect_values,
                                           guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		picolanAddressField * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = picolan_address_field_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
picolan_value_address_field_lcopy_value (const GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
	picolanAddressField ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = picolan_address_field_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
picolan_param_spec_address_field (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags)
{
	picolanParamSpecAddressField* spec;
	g_return_val_if_fail (g_type_is_a (object_type, PICOLAN_TYPE_ADDRESS_FIELD), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
picolan_value_get_address_field (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PICOLAN_TYPE_ADDRESS_FIELD), NULL);
	return value->data[0].v_pointer;
}

void
picolan_value_set_address_field (GValue* value,
                                 gpointer v_object)
{
	picolanAddressField * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PICOLAN_TYPE_ADDRESS_FIELD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PICOLAN_TYPE_ADDRESS_FIELD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		picolan_address_field_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		picolan_address_field_unref (old);
	}
}

void
picolan_value_take_address_field (GValue* value,
                                  gpointer v_object)
{
	picolanAddressField * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PICOLAN_TYPE_ADDRESS_FIELD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PICOLAN_TYPE_ADDRESS_FIELD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		picolan_address_field_unref (old);
	}
}

static void
picolan_address_field_class_init (picolanAddressFieldClass * klass,
                                  gpointer klass_data)
{
	picolan_address_field_parent_class = g_type_class_peek_parent (klass);
	((picolanAddressFieldClass *) klass)->finalize = picolan_address_field_finalize;
	g_type_class_adjust_private_offset (klass, &picolanAddressField_private_offset);
}

static void
picolan_address_field_instance_init (picolanAddressField * self,
                                     gpointer klass)
{
	self->priv = picolan_address_field_get_instance_private (self);
	self->ref_count = 1;
}

static void
picolan_address_field_finalize (picolanAddressField * obj)
{
	picolanAddressField * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PICOLAN_TYPE_ADDRESS_FIELD, picolanAddressField);
	g_signal_handlers_destroy (self);
}

GType
picolan_address_field_get_type (void)
{
	static volatile gsize picolan_address_field_type_id__volatile = 0;
	if (g_once_init_enter (&picolan_address_field_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { picolan_value_address_field_init, picolan_value_address_field_free_value, picolan_value_address_field_copy_value, picolan_value_address_field_peek_pointer, "p", picolan_value_address_field_collect_value, "p", picolan_value_address_field_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (picolanAddressFieldClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) picolan_address_field_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (picolanAddressField), 0, (GInstanceInitFunc) picolan_address_field_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType picolan_address_field_type_id;
		picolan_address_field_type_id = g_type_register_fundamental (g_type_fundamental_next (), "picolanAddressField", &g_define_type_info, &g_define_type_fundamental_info, 0);
		picolanAddressField_private_offset = g_type_add_instance_private (picolan_address_field_type_id, sizeof (picolanAddressFieldPrivate));
		g_once_init_leave (&picolan_address_field_type_id__volatile, picolan_address_field_type_id);
	}
	return picolan_address_field_type_id__volatile;
}

gpointer
picolan_address_field_ref (gpointer instance)
{
	picolanAddressField * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
picolan_address_field_unref (gpointer instance)
{
	picolanAddressField * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PICOLAN_ADDRESS_FIELD_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

