/* socket.c generated by valac 0.44.3, the Vala compiler
 * generated from socket.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <gee.h>

#define PICOLAN_TYPE_SOCKET (picolan_socket_get_type ())
#define PICOLAN_SOCKET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PICOLAN_TYPE_SOCKET, picolanSocket))
#define PICOLAN_IS_SOCKET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PICOLAN_TYPE_SOCKET))
#define PICOLAN_SOCKET_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PICOLAN_TYPE_SOCKET, picolanSocketIface))

typedef struct _picolanSocket picolanSocket;
typedef struct _picolanSocketIface picolanSocketIface;

#define PICOLAN_TYPE_INTERFACE (picolan_interface_get_type ())
#define PICOLAN_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PICOLAN_TYPE_INTERFACE, picolanInterface))
#define PICOLAN_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PICOLAN_TYPE_INTERFACE, picolanInterfaceClass))
#define PICOLAN_IS_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PICOLAN_TYPE_INTERFACE))
#define PICOLAN_IS_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PICOLAN_TYPE_INTERFACE))
#define PICOLAN_INTERFACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PICOLAN_TYPE_INTERFACE, picolanInterfaceClass))

typedef struct _picolanInterface picolanInterface;
typedef struct _picolanInterfaceClass picolanInterfaceClass;
enum  {
	PICOLAN_SOCKET_ON_DATA_SIGNAL,
	PICOLAN_SOCKET_ON_DESTROY_SIGNAL,
	PICOLAN_SOCKET_NUM_SIGNALS
};
static guint picolan_socket_signals[PICOLAN_SOCKET_NUM_SIGNALS] = {0};

struct _picolanSocketIface {
	GTypeInterface parent_iface;
	guint8 (*get_port) (picolanSocket* self);
	void (*bind) (picolanSocket* self, picolanInterface* iface);
};

GType picolan_interface_get_type (void) G_GNUC_CONST;
GType picolan_socket_get_type (void) G_GNUC_CONST;
guint8 picolan_socket_get_port (picolanSocket* self);
void picolan_socket_bind (picolanSocket* self,
                          picolanInterface* iface);

guint8
picolan_socket_get_port (picolanSocket* self)
{
	g_return_val_if_fail (self != NULL, 0U);
	return PICOLAN_SOCKET_GET_INTERFACE (self)->get_port (self);
}

void
picolan_socket_bind (picolanSocket* self,
                     picolanInterface* iface)
{
	g_return_if_fail (self != NULL);
	PICOLAN_SOCKET_GET_INTERFACE (self)->bind (self, iface);
}

static void
picolan_socket_default_init (picolanSocketIface * iface,
                             gpointer iface_data)
{
	picolan_socket_signals[PICOLAN_SOCKET_ON_DATA_SIGNAL] = g_signal_new ("on-data", PICOLAN_TYPE_SOCKET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GEE_TYPE_ARRAY_LIST);
	picolan_socket_signals[PICOLAN_SOCKET_ON_DESTROY_SIGNAL] = g_signal_new ("on-destroy", PICOLAN_TYPE_SOCKET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}

GType
picolan_socket_get_type (void)
{
	static volatile gsize picolan_socket_type_id__volatile = 0;
	if (g_once_init_enter (&picolan_socket_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (picolanSocketIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) picolan_socket_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType picolan_socket_type_id;
		picolan_socket_type_id = g_type_register_static (G_TYPE_INTERFACE, "picolanSocket", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (picolan_socket_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&picolan_socket_type_id__volatile, picolan_socket_type_id);
	}
	return picolan_socket_type_id__volatile;
}

